import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  OUTREACH_OBJECT_ID,
  OUTREACH_TITLE_FIELD_ID,
  OUTREACH_CHANNEL_FIELD_ID,
  OUTREACH_SUBJECT_FIELD_ID,
  OUTREACH_BODY_FIELD_ID,
  OUTREACH_CHARACTER_COUNT_FIELD_ID,
  OUTREACH_STATUS_FIELD_ID,
  OUTREACH_SENT_AT_FIELD_ID,
  OUTREACH_GENERATED_BY_FIELD_ID,
  OUTREACH_MODEL_FIELD_ID,
} from '../constants/universal-identifiers';

export enum OutreachChannel {
  LINKEDIN_CONNECTION = 'LINKEDIN_CONNECTION',
  LINKEDIN_FOLLOW_UP = 'LINKEDIN_FOLLOW_UP',
  COLD_EMAIL = 'COLD_EMAIL',
}

export enum OutreachStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  SENT = 'SENT',
  REPLIED = 'REPLIED',
  BOUNCED = 'BOUNCED',
}

export enum OutreachGeneratedBy {
  HUMAN = 'HUMAN',
  AGENT = 'AGENT',
}

// NOTE — undeclared `name` TEXT field on this object (see prospect.object.ts
// for the full explanation): Twenty auto-creates an unused `name` TEXT field
// (isSystem: false, label "Name") on every custom object, unconditionally,
// with no way to suppress it from an app manifest in twenty-sdk 2.31.0. This
// is expected here too — `title` is the label identifier for Outreach, so
// `name` stays blank and should be excluded from any view's visible fields.
export default defineObject({
  universalIdentifier: OUTREACH_OBJECT_ID,
  nameSingular: 'outreach',
  namePlural: 'outreaches',
  labelSingular: 'Outreach',
  labelPlural: 'Outreaches',
  description: 'A single drafted or sent touch against a prospect',
  icon: 'IconSend',
  labelIdentifierFieldMetadataUniversalIdentifier: OUTREACH_TITLE_FIELD_ID,
  fields: [
    {
      universalIdentifier: OUTREACH_TITLE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'title',
      label: 'Title',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: OUTREACH_CHANNEL_FIELD_ID,
      type: FieldType.SELECT,
      name: 'channel',
      label: 'Channel',
      icon: 'IconMessage',
      options: [
        { id: '2507434c-4eb4-4509-9cc4-34e114c2386e', value: OutreachChannel.LINKEDIN_CONNECTION, label: 'LinkedIn connection', position: 0, color: 'blue' },
        { id: 'd03bb98c-d6cf-4461-8d40-dd33b25c294f', value: OutreachChannel.LINKEDIN_FOLLOW_UP, label: 'LinkedIn follow-up', position: 1, color: 'turquoise' },
        { id: '0bc7d2f5-d013-4f75-bcdf-e7e855caddb8', value: OutreachChannel.COLD_EMAIL, label: 'Cold email', position: 2, color: 'purple' },
      ],
    },
    {
      universalIdentifier: OUTREACH_SUBJECT_FIELD_ID,
      type: FieldType.TEXT,
      name: 'subject',
      label: 'Subject',
      icon: 'IconMailOpened',
    },
    {
      universalIdentifier: OUTREACH_BODY_FIELD_ID,
      type: FieldType.TEXT,
      name: 'body',
      label: 'Body',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: OUTREACH_CHARACTER_COUNT_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'characterCount',
      label: 'Character count',
      description: 'LinkedIn connection notes must stay at or under 200',
      icon: 'IconNumbers',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: OUTREACH_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: `'${OutreachStatus.DRAFT}'`,
      options: [
        { id: '78ba2577-2e94-4ee9-8b31-897b262d27f8', value: OutreachStatus.DRAFT, label: 'Draft', position: 0, color: 'gray' },
        { id: '950d982e-f074-45eb-97f3-057211433dbc', value: OutreachStatus.APPROVED, label: 'Approved', position: 1, color: 'blue' },
        { id: '3307f7e1-f7d8-45ac-b149-947b822c2c5c', value: OutreachStatus.SENT, label: 'Sent', position: 2, color: 'orange' },
        { id: 'c14bb1c1-1e43-474a-afdd-5070df3726cf', value: OutreachStatus.REPLIED, label: 'Replied', position: 3, color: 'green' },
        { id: 'd9222177-f67b-48ac-9922-573e76e7cae4', value: OutreachStatus.BOUNCED, label: 'Bounced', position: 4, color: 'red' },
      ],
    },
    {
      universalIdentifier: OUTREACH_SENT_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'sentAt',
      label: 'Sent at',
      icon: 'IconClock',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: OUTREACH_GENERATED_BY_FIELD_ID,
      type: FieldType.SELECT,
      name: 'generatedBy',
      label: 'Generated by',
      icon: 'IconPencil',
      isNullable: true,
      options: [
        { id: 'd1b3d0e0-e2ef-461f-b3c7-3e2b815f7e4f', value: OutreachGeneratedBy.HUMAN, label: 'Human', position: 0, color: 'gray' },
        { id: '44761a89-ad9b-4bd7-84af-1e9002b1ca82', value: OutreachGeneratedBy.AGENT, label: 'Agent', position: 1, color: 'purple' },
      ],
    },
    {
      universalIdentifier: OUTREACH_MODEL_FIELD_ID,
      type: FieldType.TEXT,
      name: 'model',
      label: 'Model',
      description: 'Model id that produced this draft',
      icon: 'IconRobot',
    },
  ],
});
